[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
futures = "0.3.30"
serde = { version = "1.0.203" , features = ["derive", "std"] }
serde_yaml = "0.9.34"
tokio = { version = "1.38.0" , features = ["full"] }
